### PR TITLE
Create settings.php

### PR DESCRIPTION
**Pull request by Draky50110**
French language

### CODE REVIEW

**Comment by wilminator** [comment]
I noticed single quotes in your language strings.  Doesn't that break the PHP string using single quotes?

**Comment by wilminator** [comment]
I am in the process of adding a few more language translation settings, including for subject lines in emails.  When I am done, I would appreciate if you translated these new lines as well.  Thank you for your help with this!

**Comment by Draky50110** [comment]
No problem :)

**Comment by Draky50110** [comment]
Can't find the double quotes, did you correct the file ?

**Comment by wilminator** [comment]
I did fix it already.  My code editor led me to believe that it would have
been a problem, so I took care of it so I could merge your translations.
Again, thank you.

**Pull request merged**
